### ISSUE TITLE
Issue with addAxes

### ISSUE THREAD

**Issue by stroeum** [rohan-collins/MATLAB-GLTF#20] opened 2023-08-21 17:08 UTC
Hi,
I am currently trying to add the axes to a 3-D plot exported to GLTF.
First, I create a set of axes.
```
ax = nexttile(1);
ax.FontSize       = 8;
ax.TickDir        = 'out';
ax.CLim           = [100 5000];
ax.Colormap       = colormap('turbo');
ax.XLabel.String = 'pd (cm.Torr)';
ax.XLim          = [min(pd_q) max(pd_q)];
ax.XMinorTick    = 'on';
ax.XScale        = 'log';
ax.XTick         = logspace(-1,3,5);
ax.YLabel.String = 'pa (cm.Torr)';
ax.YLim          = [min(pa_q) max(pa_q)];
ax.YMinorTick    = 'on';
ax.YScale        = 'log';
ax.YTick         = logspace(-1,3,5);
ax.ZLabel.String = 'V_{\rm cr} (V)';
ax.ZLim          = [1e2 1e4];
ax.ZMinorTick    = 'on';
ax.ZScale        = 'log';
ax.ZTick         = logspace(2,4,3);
ax.View           = [-30,-60];
hold(ax,'on');
```
Then I try to export it using
`[gltf] = addAxes(gltf,"fontFile","ARIAL.svg",'axis',ax);`

But when I am trying to add the axes, I receive the following error. 

>     Index exceeds the number of array elements. Index must not exceed 2.
> Error in addAxes (line 634)
>                         ticklabel_node{i}(j)=gltf.addNode('mesh',ticklabel_mesh{direction(i,:)}{j},'translation',trans(j,:)*base_rotation,'rotation',rot,'addToScene',false);
> 
                        
I know addAxes is experimental, but I was wondering if you had any suggestions for me.

**Comment by rohan-collins** [comment] 2023-08-22 10:49
Hi Jeremy,

There are 3 separate issues at play here.

1. The exact error is triggered by the number of tick labels not being equal to number of ticks. This is only triggered in case of (2) below, but I have fixed this in the latest release, so at least the code won't fail, but it still won't give the result you want.
2. Your plot is log-log-log. The difference between a linear and log axis in MATLAB is only indicated by the XScale, YScale, and ZScale properties, while keeping the XLim, YLim, ZLim values the same. The function should ideally check the Scale value and use that to rescale the Lim, but I haven't had a chance to include the functionality for one of more axes being log. This is an enhancement that might take a while. (Feel free to contribute!)
3. TickLabelInterpreter being "tex". LaTeX or TeX might need to be handled using a call to a TeX distribution, but that is beyond my abilities.

The workaround for (2), till the functionality for handling log axes is added, is to rescale the data by taking logarithms before plotting - you can also reposition (by setting XTick, YTick, and ZTick) and relabel the ticks (by setting XTickLabel, YTickLabel, and ZTickLabel) to make it look more like a log axis. (Adding the functionality into the function would mean that the function does this automatically, but it will be a lot more work to account for all cases.)

Workaround for (3) is to rename the ticks using unicode text and a Unicode font that supports [Superscripts and Subscripts](https://en.wikipedia.org/wiki/Superscripts_and_Subscripts_(Unicode_block)) for exponents, and other mathematical functions (this gets progressively harder as complexity of the expression increases).

Anyway, I am taking the log axis handling as a future enhancement, and till then I hope the above can help you work around the current limitations.

Thanks,

Rohan

**Comment by rohan-collins** [comment] 2023-08-22 12:56
Since I don't have the exact inputs for your code, here is an independent example that should output a valid GLTF file:

`gltf=GLTF();`  
`ax=gca;`  
`axis equal;`  
`axis([0 1 0 1 0 1]);`  
`xlabel("log₁₀X");`  
`ylabel("log₁₀Y");`  
`zlabel("log₁₀Z");`  
`ax.XTick=log10(1:10);`  
`xticklabels(["10⁰" "" "" "" "" "" "" "" "" "10¹"]);`  
`ax.YTick=log10(1:10);`  
`yticklabels(["10⁰" "" "" "" "" "" "" "" "" "10¹"]);`  
`ax.ZTick=log10(1:10);`  
`zticklabels(["10⁰" "" "" "" "" "" "" "" "" "10¹"]);`  
`view(3);`  
`gltf=addAxes(gltf,'fontFile',"ARIAL.svg",'axis',ax);`  

Hope that helps.

Rohan

**Comment by rohan-collins** [comment] 2023-08-23 06:23
Hi Jeremy,

That is strange, since the line does not match the error. Are you sure you're using the latest version that I committed yesterday?

**Comment by stroeum** [comment] 2023-08-24 14:18
I updated to your most recent commit and was able to get close to what I need but I believe that I have still some error. 
<img width="2290" alt="Screenshot 2023-08-24 at 10 18 20 AM" src="https://github.com/rohan-collins/MATLAB-GLTF/assets/11585655/553c7910-5ed1-4928-8e7a-68ae5692f5ec">

**Comment by rohan-collins** [comment] 2023-08-24 14:25
Hi Jeremy,

I believe the issue is that you haven't rescaled the mesh itself. You will also need to take the logarithm of the coordinates of the mesh as well.

If you can share the original data (or similar), I can try helping you more. You can do it here or email me at rohan.chabukswar@collins.com.

Rohan

**Closed** 2023-08-25 15:17 UTC
Labels: enhancement

**Comment by rohan-collins** [comment] 2023-08-25 15:20
Latest update should be able to handle one or more of the axes having a log scale. LaTeX/TeX interpretation is beyond scope.

**Comment by stroeum** [comment] 2023-08-25 18:37
Awesome!

**Comment by stroeum** [comment] 2023-08-25 19:08
Hi,

A quick question, do you mean handling log axes using the method we discussed in the MWE_new, i.e., taking the log of the data? or directly using ax.XScale = “log”?

Thanks

Jeremy A. Riousset, Ph.D. (he, him, his)
Assistant Professor of Engineering Physics
Physical Science

1 Aerospace Boulevard
Daytona Beach, FL 32114
+1 (386) 226-6407
***@***.******@***.***>
https://orcid.org/0000-0003-1516-5337

Embry-Riddle Aeronautical University
Florida | Arizona | Worldwide

On Aug 25, 2023, at 2:37 PM, Jeremy Riousset ***@***.***> wrote:

Awesome!

On Aug 25, 2023, at 11:20 AM, Rohan Chabukswar ***@***.***> wrote:



Latest update should be able to handle one or more of the axes having a log scale. LaTeX/TeX interpretation is beyond scope.

**Comment by rohan-collins** [comment] 2023-08-25 20:13
The addAxes function will only work on the axes, which requires a plot. The class doesn't need a plot to work, and cannot take it as input. You will still have to take the log of the data vertices (or translations) for the scaling to work.

**Comment by stroeum** [comment] 2023-08-25 20:23
Perfect. Again thank you for your help and support. This is a terrific tool :) For what it’s worth, it got my student to earn second place in the student poster competition at URSI GASS this summer (before even getting the axes working :) )

https://www.ursi-gass2023.jp/

Best

**Comment by rohan-collins** [comment] 2023-08-28 09:39
That's great to know! Cheers,

Rohan
